version: '3.3'

services:

  db:
    image: mysql:8.0.21
    build: .
    environment:
      MYSQL_USER: lena
      MYSQL_PASSWORD: lena1711
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flightsTestTask

  app:
    container_name: flights-test-task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/flightsTestTask?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: lena
      SPRING_DATASOURCE_PASSWORD: lena1711

    depends_on:
      - db