version: '3.3'

services:

  db:
    image: mysql:8.0.21
    build: .
    environment:
      MYSQL_USER: lena
      MYSQL_PASSWORD: lena1711
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flightsTestTask
    ports:
      - "3307:3306"
    networks:
      - common-network

  app:
    container_name: flights-test-task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - common-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flightsTestTask?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: lena
      SPRING_DATASOURCE_PASSWORD: lena1711

    depends_on:
      - db

networks:
  common-network:
    driver: bridge